export const projects = [
  {
    title: 'Restaurant App',
    description: " have developed the application on React Native on both OS systems. The app works like the FoodPand app. The flow is the users, sign's in, and then can select the category. Once done with that all the restaurants that have that category, it will be displayed. The user will then place the order and it will be added to the cart. Once checking out it had the payment gateway as well. Also, the user can track its order through live tracking implementation in the map.",
    image: '/images/RESTURANT-MOCKUP.jpg',
    tags: ['React Native', 'Java', 'Firebase', 'Rest API'],
    source: 'https://github.com/Coders-Of-XDA-OT/covid19-status-android',
    visit: 'https://project.vipuljha.com/covid/',
    id: 0,
  },
  {
    title: 'Food Delivery App',
    description: "In this app, the key implementation was, Push Notification through FCM, Google Maps API integration. Part of Restaurant App. Can be used in various apps like any traveling booking app.",
    image: '/images/FOOD-MOCKUP.jpg',
    tags: ['Javascript', 'React Native', 'Bootstrap', 'ES6'],
    source: 'https://github.com/lordarcadius/website',
    visit: 'https://project.vipuljha.com/website/',
    id: 1,
  },
  {
    title: 'Bata App',
    description: "This application is based on providing the service similarly, like UBER, and various apps, the difference was it provides us the translators, for different languages. a user can book any translator on hourly basis, based on the translator's profile and reviews.",
    image: '/images/BATA.jpg',
    tags: ['Live Tracking', 'React Native', "Node", "Express"],
    source: 'https://github.com/lordarcadius/ABS-Tweaks',
    visit: 'https://forum.xda-developers.com/t/tweak-mod-arm-x86-project-dark-booster-abs-tweaks-v5-0-2-3-6-0-23-01-2016.3120404/',
    id: 2,
  },
  {
    title: 'Run Mator App',
    description: "This app was developed to have services of Mechanic for a user. If the user is stucked at somewhere in between, the user just opens this up and can declare it's issue and can book any mechanic for the respective service.",
    image: '/images/RUN-MATOR.jpg',
    tags: ['Firebase', 'React Native', 'Java', 'XML'],
    source: 'https://github.com/lordarcadius/electrablue_mido',
    visit: 'https://forum.xda-developers.com/t/kernel-mido-oreo-pie-electrablue-kernel-21-0-july-06-redmi-note-4.3655651/',
    id: 3,
  },
  {
    title: 'Bmad App',
    description: "This app's main motive app was to interact with people. In this app when the user sign's in, the user will be seeing all the users present in that users particular area, later the user can invite any respective user on a certain time and restaurant for having a drink or food. Then user can either accept or reject the proposal.",
    image: '/images/BMAD-MOCKUP.jpg',
    tags: ['React Native', 'Map', 'FCM', 'XML'],
    source: '#',
    visit: 'https://forum.xda-developers.com/t/app-port-6-0-lenovo-snapit-camera-5-8-53-for-all-devices.3608065/',
    id: 3,
  },
  {
    title: 'Ticket Booking App',
    description: "This app was developed for booking the tickets of AirLine. Internationally as well as for local travel. This app considered all the airlines data, implemented paymenyt gateway as well ",
    image: '/images/BOOKING-MOCKUP.jpg',
    tags: ['React Native', 'Firebase', 'FCM'],
    source: '#',
    visit: 'https://forum.xda-developers.com/t/c-apps-v2-unofficial-6-0-x-cyanogen-os-capps-v2-for-cm13-and-cm13-based-roms.3254865/',
    id: 3,
  },

];

export const TimeLineData = [
  { year: 2015, text: 'At the start of my professional career in 2015 I decided to move towards Mobile App Development and got basic grip on JAVA.  ', },
  { year: 2016, text: 'Moved towards cross-platform and learned React Naitve.', },
  { year: 2017, text: 'Started my journey as a React Front-End developer.', },
  { year: 2018, text: 'Worked as a Jr. React and React Native developer.', },
  { year: 2019, text: 'Finished Graduation in Software Engineering.', },
  { year: 2020, text: 'Started MERN Stack development.', },
  { year: 2021, text: "Current Designation is Sr.Executive in Mobile Application Department ", },
];